In [1]:
#Airline dataset task using pandas.

!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [8]:
data = pd.read_csv("AirlineDataset.csv")
data

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed

In [9]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98619 entries, 0 to 98618
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Passenger ID          98619 non-null  int64
 1   First Name            98619 non-null  object
 2   Last Name             98619 non-null  object
 3   Gender                98619 non-null  object
 4   Age                   98619 non-null  int64
 5   Nationality           98619 non-null  object
 6   Airport Name          98619 non-null  object
 7   Airport Country Code  98619 non-null  object
 8   Country Name          98619 non-null  object
 9   Airport Continent     98619 non-null  object
 10  Continents            98619 non-null  object
 11  Departure Date        98619 non-null  object
 12  Arrival Airport       98619 non-null  object
 13  Pilot Name            98619 non-null  object
 14  Flight Status         98619 non-null  object
dtypes: int64(2), object(13)
memory usage: 11.3+ MB

       Passenger ID           Age
count  98619.000000  98619.000000
mean   55168.689522     45.504021
std    25985.443696     25.929849
min    10000.000000      1.000000
25%    32608.000000     23.000000
50%    55338.000000     46.000000
75%    77695.000000     68.000000
max    99999.000000     90.000000

In [10]:
data.head()

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time

In [11]:
data.tail()

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed

In [12]:
data.loc[67453, 'Country Name']

'Afghanistan'

In [13]:
data.loc[7453, 'Airport Name']

'Murrin Murrin Airport'

In [14]:
print(data.iloc[3:15,[1,8]])

   First Name    Country Name
3    Dominica          Canada
4         Bay   United States
5        Lora          Brazil
6        Rand  United Kingdom
7    Perceval          Brazil
8       Aleda           Italy
9      Burlie          Canada
10      Porty          Mexico
11     Briant          Panama
12      Kalie        Pakistan
13   Catriona       Australia
14    Amberly   United States

In [15]:
data["Amount"] = np.random.randint(10000, 100001, size=len(data))
data

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Amount
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time,18964
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time,16634
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time,97936
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed,99751
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time,72765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled,22824
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled,24397
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time,51198
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled,76732
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed,11587

In [16]:
print(data.iloc[:15,[1,6,12,15]])

   First Name                       Airport Name Arrival Airport  Amount
0      Edithe                   Coldfoot Airport             CXF   18964
1      Elwood                  Kugluktuk Airport             YCO   16634
2       Darby             Grenoble-Isère Airport             GNB   97936
3    Dominica          Ottawa / Gatineau Airport             YND   99751
4         Bay                    Gillespie Field             SEE   72765
5        Lora  Coronel Horácio de Mattos Airport             LEC   81698
6        Rand                  Duxford Aerodrome             QFO   89978
7    Perceval     Maestro Wilson Fonseca Airport             STM   26209
8       Aleda          Venice Marco Polo Airport             VCE   49410
9      Burlie                  Vermilion Airport             YVG   74834
10      Porty        Nuevo Casas Grandes Airport             NCG   93246
11     Briant                Ruben Cantu Airport             SYP   20342
12      Kalie                    Loralai Airport             LRG   39570
13   Catriona                      Cudal Airport             CUG   15670
14    Amberly        Farmington Regional Airport             FAM   42954

In [17]:
data["category"]=data['Age'].apply(lambda x: "senior" if x > 50 else ("adult" if x >= 18 else "child"))
data

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Amount,category
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time,18964,senior
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time,16634,senior
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time,97936,senior
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed,99751,senior
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time,72765,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled,22824,senior
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled,24397,adult
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time,51198,senior
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled,76732,adult
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed,11587,child

In [18]:
data["category"] = pd.Categorical(data["category"])
print(data["category"].cat.categories)
print(data["category"].value_counts())

Index(['adult', 'child', 'senior'], dtype='object')
category
senior    43831
adult     36241
child     18547
Name: count, dtype: int64

In [19]:
data["Flight Status"] = pd.Categorical(data["Flight Status"])
print(data["Flight Status"].cat.categories)
print(data["Flight Status"].value_counts())

Index(['Cancelled', 'Delayed', 'On Time'], dtype='object')
Flight Status
Cancelled    32942
On Time      32846
Delayed      32831
Name: count, dtype: int64

In [20]:
data.T

,0,1,2,3,4,5,6,7,8,9,...,98609,98610,98611,98612,98613,98614,98615,98616,98617,98618
Passenger ID,10856,43872,42633,78493,82072,39630,11940,26470,29447,75035,...,70741,87872,37761,26208,95651,58454,22028,61732,19819,14485
First Name,Edithe,Elwood,Darby,Dominica,Bay,Lora,Rand,Perceval,Aleda,Burlie,...,Olimpia,Che,Hadria,Ody,Oneida,Gareth,Kasey,Darrin,Gayle,Wilhelmine
Last Name,Leggis,Catt,Felgate,Pyle,Pencost,Durbann,Bram,Dallosso,Pigram,Schustl,...,Arstall,Pressland,Vacher,Tineman,Ossipenko,Mugford,Benedict,Lucken,Lievesley,Touret
Gender,Female,Male,Male,Female,Male,Female,Male,Male,Female,Male,...,Female,Male,Female,Male,Female,Male,Female,Male,Female,Female
Age,62,62,67,71,21,55,73,36,35,13,...,22,83,41,82,47,85,19,65,34,10
Nationality,Japan,Nicaragua,Russia,China,China,Brazil,Ivory Coast,Vietnam,Palestinian Territory,Thailand,...,China,France,Canada,Indonesia,Serbia,China,Russia,Indonesia,China,Poland
Airport Name,Coldfoot Airport,Kugluktuk Airport,Grenoble-Isère Airport,Ottawa / Gatineau Airport,Gillespie Field,Coronel Horácio de Mattos Airport,Duxford Aerodrome,Maestro Wilson Fonseca Airport,Venice Marco Polo Airport,Vermilion Airport,...,Wuzhou Changzhoudao Airport,Warangal Airport,Ipil Airport,Five Mile Airport,Arugam Bay SPB,Hasvik Airport,Ampampamena Airport,Albacete-Los Llanos Airport,Gagnoa Airport,Yoshkar-Ola Airport
Airport Country Code,US,CA,FR,CA,US,BR,GB,BR,IT,CA,...,CN,IN,PH,US,LK,NO,MG,ES,CI,RU
Country Name,United States,Canada,France,Canada,United States,Brazil,United Kingdom,Brazil,Italy,Canada,...,China,India,Philippines,United States,Sri Lanka,Norway,Madagascar,Spain,Côte d'Ivoire,Russian Federation
Airport Continent,NAM,NAM,EU,NAM,NAM,SAM,EU,SAM,EU,NAM,...,AS,AS,AS,NAM,AS,EU,AF,EU,AF,EU
Continents,North America,North America,Europe,North America,North America,South America,Europe,South America,Europe,North America,...,Asia,Asia,Asia,North America,Asia,Europe,Africa,Europe,Africa,Europe
Departure Date,6/28/2022,12/26/2022,1/18/2022,9/16/2022,2/25/2022,6/10/2022,10/30/2022,4/7/2022,8/20/2022,4/6/2022,...,4/23/2022,8/5/2022,6/6/2022,3/17/2022,5/12/2022,12/11/2022,10/30/2022,9/10/2022,10/26/2022,4/16/2022
Arrival Airport,CXF,YCO,GNB,YND,SEE,LEC,QFO,STM,VCE,YVG,...,WUZ,WGC,IPE,FMC,AYY,HAA,IVA,ABC,GGN,JOK
Pilot Name,Edithe Leggis,Elwood Catt,Darby Felgate,Dominica Pyle,Bay Pencost,Lora Durbann,Rand Bram,Perceval Dallosso,Aleda Pigram,Burlie Schustl,...,Olimpia Arstall,Che Pressland,Hadria Vacher,Ody Tineman,Oneida Ossipenko,Gareth Mugford,Kasey Benedict,Darrin Lucken,Gayle Lievesley,Wilhelmine Touret
Flight Status,On Time,On Time,On Time,Delayed,On Time,On Time,Cancelled,Cancelled,On Time,On Time,...,On Time,Cancelled,On Time,Delayed,Delayed,Cancelled,Cancelled,On Time,Cancelled,Delayed
Amount,18964,16634,97936,99751,72765,81698,89978,26209,49410,74834,...,72143,16003,50058,77292,90140,22824,24397,51198,76732,11587
category,senior,senior,senior,senior,adult,senior,senior,adult,adult,child,...,adult,senior,adult,senior,adult,senior,adult,senior,adult,child

In [21]:
data["Amount"] = data["Amount"].astype(float)
print(data["Amount"].dtypes)
print(data.iloc[:15,[15]])

float64
     Amount
0   18964.0
1   16634.0
2   97936.0
3   99751.0
4   72765.0
5   81698.0
6   89978.0
7   26209.0
8   49410.0
9   74834.0
10  93246.0
11  20342.0
12  39570.0
13  15670.0
14  42954.0

In [22]:
data.groupby("Flight Status", observed=True)["Amount"].mean()

Flight Status
Cancelled    54872.120849
Delayed      54999.096616
On Time      54787.600560
Name: Amount, dtype: float64

In [23]:
data.groupby("Gender", observed=True)["Amount"].mean()

Gender
Female    54954.064870
Male      54819.207629
Name: Amount, dtype: float64

In [24]:
data.groupby("Flight Status", observed=True)["Amount"].median()

Flight Status
Cancelled    54599.5
Delayed      54939.0
On Time      54659.0
Name: Amount, dtype: float64

In [ ]:
data.groupby("Flight Status", observed=True)["Amount"].max()

Flight Status
Cancelled    99999.0
Delayed      99993.0
On Time      99998.0
Name: Amount, dtype: float64

In [25]:
data.groupby("Airport Country Code", observed=True)["Amount"].median()

Airport Country Code
AD    44711.0
AE    60928.5
AF    53273.5
AG    56662.5
AI    56889.0
       ...
YE    56622.0
YT    64821.0
ZA    52481.0
ZM    55188.0
ZW    53837.0
Name: Amount, Length: 235, dtype: float64

In [28]:
data['Nationality'].values

array(['Japan', 'Nicaragua', 'Russia', ..., 'Indonesia', 'China',
       'Poland'], dtype=object)

In [29]:
display(data["Nationality"].value_counts())

Nationality
China                          18317
Indonesia                      10559
Russia                          5693
Philippines                     5239
Brazil                          3791
                               ...
French Southern Territories        2
Saint Martin                       2
Norfolk Island                     1
Jersey                             1
Sint Maarten                       1
Name: count, Length: 240, dtype: int64

In [30]:
data[data.Continents=='Europe'].head(10)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Amount,category
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time,97936.0,senior
6,11940,Rand,Bram,Male,73,Ivory Coast,Duxford Aerodrome,GB,United Kingdom,EU,Europe,10/30/2022,QFO,Rand Bram,Cancelled,89978.0,senior
8,29447,Aleda,Pigram,Female,35,Palestinian Territory,Venice Marco Polo Airport,IT,Italy,EU,Europe,8/20/2022,VCE,Aleda Pigram,On Time,49410.0,adult
73,25310,Diannne,Samter,Female,73,Cameroon,Vadsø Airport,NO,Norway,EU,Europe,11/25/2022,VDS,Diannne Samter,Cancelled,99842.0,senior
76,97267,Ajay,Durward,Female,26,Russia,João Paulo II Airport,PT,Portugal,EU,Europe,8/26/2022,PDL,Ajay Durward,On Time,47644.0,adult
92,46273,Aeriela,Clarke,Female,70,Portugal,Gorna Oryahovitsa Airport,BG,Bulgaria,EU,Europe,9/25/2022,GOZ,Aeriela Clarke,On Time,59575.0,senior
94,99708,Rodolph,Grewcock,Male,23,Kazakhstan,Nalchik Airport,RU,Russian Federation,EU,Europe,11/26/2022,NAL,Rodolph Grewcock,Delayed,37382.0,adult
99,16470,Ebony,Knappitt,Female,7,Russia,Genoa Cristoforo Colombo Airport,IT,Italy,EU,Europe,12/18/2022,GOA,Ebony Knappitt,On Time,59263.0,child
113,65726,Artemus,Brewitt,Male,27,China,Fáskrúðsfjörður Airport,IS,Iceland,EU,Europe,1/13/2022,FAS,Artemus Brewitt,On Time,19014.0,adult
116,86568,Reinaldo,Caines,Male,76,Indonesia,Newcastle Airport,GB,United Kingdom,EU,Europe,3/17/2022,NCL,Reinaldo Caines,On Time,53029.0,senior