In [ ]:
!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
s1 = pd.Series([50,76,81,20,90])
s2 = pd.Series([50,7.6,81,20,90])
s3 = pd.Series([50,76,81,20,'abc'])
print(s1)
print(s2)
print(s3)

0    50
1    76
2    81
3    20
4    90
dtype: int64
0    50.0
1     7.6
2    81.0
3    20.0
4    90.0
dtype: float64
0     50
1     76
2     81
3     20
4    abc
dtype: object

In [ ]:
s4 = pd.Series([65,77,53,67,90], index = ['Maths','Science','Social','Kannada','Hindi'])
s4

Maths      65
Science    77
Social     53
Kannada    67
Hindi      90
dtype: int64

In [ ]:
#s5 = pd.Series([50,76,81,99,20], index = ['a','b','c','d','e'], dtype = 'float' )
#s5 = pd.Series([50,76,81,99,20], index = ['a','b','c','d','e'], dtype = 'object' )
#s5 = pd.Series([50,76,81,99,20], index = ['a','b','c','d','e'], dtype = 'int' )
s5

a    50
b    76
c    81
d    99
e    20
dtype: int64

In [9]:
s6 = pd.Series({'fruit1':'Apple', 'fruit2':'Mango', 'fruit3':'Grapes'})
s6

fruit1     Apple
fruit2     Mango
fruit3    Grapes
dtype: object

In [11]:
d1 = pd.DataFrame([43,82,70,99])
d1

    0
0  43
1  82
2  70
3  99

In [31]:
d2 = pd.DataFrame([[2,3,4],[6,7,8],[9,10,11]],columns=['A','B','C'], index=['X','Y','Z'])
d2

   A   B   C
X  2   3   4
Y  6   7   8
Z  9  10  11

In [13]:
d3 = pd.DataFrame([[2,4,6],[8,10,12],[14,16,18]], columns=['std1','std2','std3'])
d3

   std1  std2  std3
0     2     4     6
1     8    10    12
2    14    16    18

In [16]:
d2 = pd.DataFrame(s2)
d2

      0
0  50.0
1   7.6
2  81.0
3  20.0
4  90.0

In [69]:
d3 = pd.DataFrame([[52,49,56],[81,70,72],[94,66,88]], columns=['exam1','exam2','exam3'], index=['tina','sana','myra'])
d3

      exam1  exam2  exam3
tina     52     49     56
sana     81     70     72
myra     94     66     88

In [22]:
d4 = [{'tina':87,'myra':22},{'sana':12,'tina':49,'riya':44},{'myra':50,'sana':70,'riya':64}]
pd.DataFrame(d4,index = ['no1','no2','no3'])

     tina  myra  sana  riya
no1  87.0  22.0   NaN   NaN
no2  49.0   NaN  12.0  44.0
no3   NaN  50.0  70.0  64.0

In [70]:
d3

      exam1  exam2  exam3
tina     52     49     56
sana     81     70     72
myra     94     66     88

In [71]:
print(d3['exam3'])

tina    56
sana    72
myra    88
Name: exam3, dtype: int64

In [72]:
d3['total']=d3['exam1']+d3['exam2']+d3['exam3']
d3['Avg'] = d3['total']/3
d3

      exam1  exam2  exam3  total        Avg
tina     52     49     56    157  52.333333
sana     81     70     72    223  74.333333
myra     94     66     88    248  82.666667

In [73]:
pop = d3.pop('Avg')
d3

      exam1  exam2  exam3  total
tina     52     49     56    157
sana     81     70     72    223
myra     94     66     88    248

In [74]:
del d3['total']
d3

      exam1  exam2  exam3
tina     52     49     56
sana     81     70     72
myra     94     66     88

In [76]:
d3.insert(3,'exam4',d3['exam2'])
d3

      exam1  exam2  exam3  exam4
tina     52     49     56     49
sana     81     70     72     70
myra     94     66     88     66

In [77]:
d = {'exam1':70,'exam2':70,'exam3':45,'exam4':80}
df1 = d3._append(d,ignore_index=True)
df1

   exam1  exam2  exam3  exam4
0     52     49     56     49
1     81     70     72     70
2     94     66     88     66
3     70     70     45     80

In [80]:
import numpy as np
d5 = pd.DataFrame({'emp1':np.random.randint(10,20,size=(10)),'emp2':np.random.randint(20,30,size=(10)),'emp3':np.random.randint(30,40,size=(10))})
d5

   emp1  emp2  emp3
0    13    29    38
1    15    22    37
2    12    23    35
3    15    21    30
4    17    21    31
5    10    22    32
6    18    21    36
7    10    26    39
8    17    26    38
9    13    27    36

In [83]:
#d5.head()
#d5.tail()

   emp1  emp2  emp3
5    10    22    32
6    18    21    36
7    10    26    39
8    17    26    38
9    13    27    36

In [84]:
d5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   emp1    10 non-null     int64
 1   emp2    10 non-null     int64
 2   emp3    10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

In [85]:
d5.describe()

            emp1       emp2       emp3
count  10.000000  10.000000  10.000000
mean   14.000000  23.800000  35.200000
std     2.867442   2.936362   3.155243
min    10.000000  21.000000  30.000000
25%    12.250000  21.250000  32.750000
50%    14.000000  22.500000  36.000000
75%    16.500000  26.000000  37.750000
max    18.000000  29.000000  39.000000

In [86]:
d5

   emp1  emp2  emp3
0    13    29    38
1    15    22    37
2    12    23    35
3    15    21    30
4    17    21    31
5    10    22    32
6    18    21    36
7    10    26    39
8    17    26    38
9    13    27    36

In [87]:
print(d5.loc[5,'emp2'])

22

In [88]:
d5.loc[6:9,['emp1','emp3']]

   emp1  emp3
6    18    36
7    10    39
8    17    38
9    13    36

In [90]:
d5.loc[[2,5,9],['emp1','emp3']]

   emp1  emp3
2    12    35
5    10    32
9    13    36

In [94]:
print(d5.iloc[7,1])

26

In [97]:
d5.iloc[3:8,[0,2]]

   emp1  emp3
3    15    30
4    17    31
5    10    32
6    18    36
7    10    39

In [98]:
d5.emp2.values

array([29, 22, 23, 21, 21, 22, 21, 26, 26, 27])

In [104]:
d5['sub'] = d5.emp1.values - d5.emp2.values + d5.emp3.values
d5

   emp1  emp2  emp3  sub
0    13    29    38   22
1    15    22    37   30
2    12    23    35   24
3    15    21    30   24
4    17    21    31   27
5    10    22    32   20
6    18    21    36   33
7    10    26    39   23
8    17    26    38   29
9    13    27    36   22